development:
  adapter: postgresql
  encoding: unicode
  database: Restaurante
  pool: 5
  port: 1470
  password: 654321

test:
  adapter: postgresql
  encoding: unicode
  database: Restaurante
  pool: 5
  port: 1470
  password: 654321

production:
  adapter: postgresql
  encoding: unicode
  database: Restaurante
  pool: 5
  port: 1470
  password: 654321
